/* This file was generated by syncqt. */
#ifndef QT_QASEMANSQL_VERSION_H
#define QT_QASEMANSQL_VERSION_H

#define QASEMANSQL_VERSION_STR "3.1.5"

#define QASEMANSQL_VERSION 0x030105

#endif // QT_QASEMANSQL_VERSION_H
