/* This file was generated by syncqt. */
#ifndef QT_QASEMANGEO_VERSION_H
#define QT_QASEMANGEO_VERSION_H

#define QASEMANGEO_VERSION_STR "3.1.5"

#define QASEMANGEO_VERSION 0x030105

#endif // QT_QASEMANGEO_VERSION_H
