/* This file was generated by syncqt. */
#ifndef QT_QASEMANGUI_VERSION_H
#define QT_QASEMANGUI_VERSION_H

#define QASEMANGUI_VERSION_STR "3.1.5"

#define QASEMANGUI_VERSION 0x030105

#endif // QT_QASEMANGUI_VERSION_H
