#ifndef ASEMAN_MULTIMEDIA_GLOBAL_H
#define ASEMAN_MULTIMEDIA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#if defined(LIBQTASEMAN_MULTIMEDIA_LIBRARY)
#  define LIBQTASEMAN_MULTIMEDIA_EXPORT Q_DECL_EXPORT
#else
#  define LIBQTASEMAN_MULTIMEDIA_EXPORT Q_DECL_IMPORT
#endif
#else
#define LIBQTASEMAN_MULTIMEDIA_EXPORT
#endif

#endif // ASEMAN_MULTIMEDIA_GLOBAL_H
