/* This file was generated by syncqt. */
#ifndef QT_QASEMANQML_VERSION_H
#define QT_QASEMANQML_VERSION_H

#define QASEMANQML_VERSION_STR "3.1.5"

#define QASEMANQML_VERSION 0x030105

#endif // QT_QASEMANQML_VERSION_H
